SELECT *
FROM customer
limit 20



-- Q1. What is the total revenue generated by male vs. female customers?
SELECT c.gender, SUM(c.purchase_amount) as revenue
FROM customer c
GROUP BY c.gender


-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT c.customer_id, c.purchase_amount
FROM customer c
WHERE (c.discount_applied = 'Yes' and c.purchase_amount >= 
	(
	SELECT AVG(c.purchase_amount) 
	FROM customer c
	)
)


-- Q3. Which are the top 5 products with the highest average review rating?
SELECT c.item_purchased, ROUND(AVG(c.review_rating)::numeric, 2) as "Average Product Rating"
FROM customer c
GROUP BY c.item_purchased
ORDER BY AVG(c.review_rating) DESC
LIMIT 5;


-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT c.shipping_type, ROUND(AVG(c.purchase_amount)::numeric, 2)
FROM customer c
WHERE (c.shipping_type in ('Standard', 'Express'))
GROUP BY c.shipping_type


-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT c.subscription_status, COUNT(c.customer_id) as total_customers, ROUND(AVG(c.purchase_amount)::numeric, 2) as avg_spend, ROUND(SUM(c.purchase_amount)::numeric, 2) as total_revenue
FROM customer c
GROUP BY c.subscription_status
ORDER BY total_revenue, avg_spend DESC;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT c.item_purchased, ROUND(((SUM(CASE WHEN c.discount_applied = 'Yes' THEN 1 ELSE 0 END)::numeric / COUNT(*)) * 100), 2) as discount_rate
FROM customer c
Group BY c.item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
WITH customer_type as (SELECT c.customer_id, c.previous_purchases, 
						CASE WHEN c.previous_purchases = 1 THEN 'New' WHEN c.previous_purchases > 1 and c.previous_purchases <= 10 THEN 'Returning' ELSE 'Loyal' END AS customer_segment 
						FROM customer c)
SELECT customer_segment, COUNT(*) as "Number of Customers"
FROM customer_type
GROUP BY customer_segment;

-- Q8. What are the top 3 most purchased products within each category?
WITH item_counts as (SELECT c.category, c.item_purchased, COUNT(c.customer_id) as total_orders, ROW_NUMBER() OVER (PARTITION BY c.category ORDER BY COUNT(c.customer_id) DESC) as item_rank 
					 FROM customer c
					 GROUP BY c.category, c.item_purchased)
SELECT item_rank, item_counts.category, item_counts.item_purchased, total_orders
FROM item_counts
WHERE (item_rank <= 3);



-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT c.subscription_status, COUNT(c.customer_id) as repeat_buyers
FROM customer c
WHERE c.previous_purchases > 5
GROUP BY c.subscription_status;


-- Q10. What is the revenue contribution of each age group?
SELECT c.age_group, SUM(c.purchase_amount) as total_revenue
FROM customer c
GROUP BY c.age_group
ORDER BY total_revenue ASC;
